linters:
  enable:
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - ineffassign
    - govet
    - unused
    - misspell
  disable:
    - errcheck

linters-settings:
  revive:
    rules:
      # TODO(thaJeztah): temporarily disabled the "unused-parameter" check.
      # It produces many warnings, and some of those may need to be looked at.
      - name: unused-parameter
        disabled: true

run:
  deadline: 2m

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    # io/ioutil is deprecated, but won't be removed until Go v2. It's safe to ignore for the release/2.8 branch.
    # The wording of the staticcheck message changed ("since Go 1.16" -> "since Go 1.19"), so match either.
    - text: "SA1019: \"io/ioutil\" has been deprecated since Go 1\\.(16|19)"
      linters:
        - staticcheck
